/**
 * Types for the sampler orchestrator
 *
 * The sampler generates diverse vignettes (text snippets with embeddings) from raw data
 * for the Analyser Agent to examine and identify data types.
 */

import type {Chunk} from './chunkText';

/**
 * Position of a vignette in the original data
 */
export interface VignettePosition {
	/**
	 * Character offset where content starts
	 */
	start: number;

	/**
	 * Character offset where content ends
	 */
	end: number;
}

/**
 * A vignette is a text snippet with its embedding and position in the original data
 *
 * Used by the Analyser Agent to examine diverse samples of the data without
 * processing the entire dataset.
 */
export interface Vignette {
	/**
	 * Text content of the vignette
	 */
	content: string;

	/**
	 * Position in the original raw data (before trimming)
	 */
	position: VignettePosition;

	/**
	 * 384-dimensional embedding vector
	 *
	 * Generated by all-MiniLM-L6-v2 model, normalised for cosine similarity.
	 */
	embedding: number[];
}

/**
 * State maintained across sampling operations
 *
 * Allows incremental sampling - the agent can request more samples without
 * reprocessing the entire dataset. Tracks which chunks have already been provided.
 */
export interface SamplerState {
	/**
	 * Original input data (untrimmed)
	 *
	 * Preserved for position reference and potential future sampling.
	 */
	rawData: string;

	/**
	 * All chunks with position metadata
	 *
	 * Computed once during initial sampling, reused for subsequent requests.
	 */
	allChunks: Chunk[];

	/**
	 * All embeddings corresponding to allChunks
	 *
	 * 384-dimensional vectors in same order as allChunks.
	 * Computed once during initial sampling, reused for subsequent requests.
	 */
	allEmbeddings: number[][];

	/**
	 * Indices of chunks already provided to the agent
	 *
	 * Used to ensure no duplicate vignettes are sent. Indices correspond
	 * to positions in allChunks and allEmbeddings arrays.
	 */
	providedIndices: Set<number>;
}

/**
 * Result from generating initial vignettes
 */
export interface InitialVignettesResult {
	/**
	 * Generated vignettes
	 */
	vignettes: Vignette[];

	/**
	 * State for future sampling operations
	 */
	state: SamplerState;
}

/**
 * Result from requesting more samples
 */
export interface MoreSamplesResult {
	/**
	 * Additional vignettes
	 */
	vignettes: Vignette[];

	/**
	 * Updated state with new providedIndices
	 */
	newState: SamplerState;

	/**
	 * Whether more samples are available
	 */
	hasMore: boolean;
}
