/**
 * Zod schemas for application-level log events
 *
 * Defines log events specific to the Sigil data processing pipeline, including
 * preprocessing (chunking, embedding), agent orchestration (Analyser, GenerateSigilIR),
 * and request lifecycle events (cancellation, errors).
 *
 * These events are distinct from framework events (defined in events.ts) which are
 * reusable across any agent execution.
 */

import {z} from 'zod';

import {TokenMetricsSchema} from '@sigil/src/agent/framework';

import {PinoLogBaseSchema} from './baseSchema';

/**
 * Preprocessing start event
 *
 * Fired when data preprocessing begins (before agent execution).
 */
export const PreprocessingStartEventSchema = PinoLogBaseSchema.extend({
	event: z.literal('preprocessing_start'),
	data: z.object({}).optional(),
});

export type PreprocessingStartEvent = z.infer<typeof PreprocessingStartEventSchema>;

/**
 * Chunking complete event
 *
 * Fired when data chunking completes during preprocessing.
 */
export const ChunkingCompleteEventSchema = PinoLogBaseSchema.extend({
	event: z.literal('chunking_complete'),
	data: z.object({
		chunkCount: z.number().int().positive().describe('Number of chunks created'),
		dataSizeKB: z.string().describe('Data size in kilobytes (formatted string)'),
	}),
});

export type ChunkingCompleteEvent = z.infer<typeof ChunkingCompleteEventSchema>;

/**
 * Embedding progress event
 *
 * Fired during embedding generation to report progress.
 */
export const EmbeddingProgressEventSchema = PinoLogBaseSchema.extend({
	event: z.literal('embedding_progress'),
	data: z.object({
		current: z.number().int().nonnegative().describe('Number of embeddings generated so far'),
		total: z.number().int().positive().describe('Total number of embeddings to generate'),
	}),
});

export type EmbeddingProgressEvent = z.infer<typeof EmbeddingProgressEventSchema>;

/**
 * Vignettes generated event
 *
 * Fired when initial vignettes (diverse data samples) are generated.
 */
export const VignettesGeneratedEventSchema = PinoLogBaseSchema.extend({
	event: z.literal('vignettes_generated'),
	data: z.object({
		vignetteCount: z.number().int().positive().describe('Number of vignettes generated'),
	}),
});

export type VignettesGeneratedEvent = z.infer<typeof VignettesGeneratedEventSchema>;

/**
 * Analyser complete event
 *
 * Fired when the Analyser agent completes successfully.
 */
export const AnalyserCompleteEventSchema = PinoLogBaseSchema.extend({
	event: z.literal('analyser_complete'),
	data: z.object({
		metadata: z.object({
			attempts: z.number().int().positive(),
			latency: z.number().optional(),
			tokens: TokenMetricsSchema.optional(),
		}).describe('Execution metadata from analyser'),
	}),
});

export type AnalyserCompleteEvent = z.infer<typeof AnalyserCompleteEventSchema>;

/**
 * Spec generated event
 *
 * Fired when a component spec is generated by GenerateSigilIR agent.
 */
export const SpecGeneratedEventSchema = PinoLogBaseSchema.extend({
	event: z.literal('spec_generated'),
	data: z.object({
		spec: z.unknown().describe('Generated component spec'),
	}),
});

export type SpecGeneratedEvent = z.infer<typeof SpecGeneratedEventSchema>;

/**
 * Request cancelled event
 *
 * Fired when a request is cancelled by the client.
 */
export const RequestCancelledEventSchema = PinoLogBaseSchema.extend({
	event: z.literal('request_cancelled'),
	data: z.object({
		phase: z.string().optional().describe('Phase where cancellation occurred (e.g., "execution", "preprocessing")'),
		error: z.unknown().optional().describe('Error details or error object'),
	}),
});

export type RequestCancelledEvent = z.infer<typeof RequestCancelledEventSchema>;

/**
 * Client disconnected event
 *
 * Fired when the client disconnects during request processing.
 */
export const ClientDisconnectedEventSchema = PinoLogBaseSchema.extend({
	event: z.literal('client_disconnected'),
	data: z.object({}).optional(),
});

export type ClientDisconnectedEvent = z.infer<typeof ClientDisconnectedEventSchema>;

/**
 * Unexpected error event
 *
 * Fired when an unexpected error occurs (catch-all for non-agent errors).
 */
export const UnexpectedErrorEventSchema = PinoLogBaseSchema.extend({
	event: z.literal('unexpected_error'),
	data: z.object({
		error: z.string().describe('Error message or description'),
	}),
});

export type UnexpectedErrorEvent = z.infer<typeof UnexpectedErrorEventSchema>;

/**
 * Discriminated union of all application-level log events
 *
 * Use the `event` field to narrow the type in switch statements or type guards.
 */
export const ApplicationLogEventSchema = z.discriminatedUnion('event', [
	PreprocessingStartEventSchema,
	ChunkingCompleteEventSchema,
	EmbeddingProgressEventSchema,
	VignettesGeneratedEventSchema,
	AnalyserCompleteEventSchema,
	SpecGeneratedEventSchema,
	RequestCancelledEventSchema,
	ClientDisconnectedEventSchema,
	UnexpectedErrorEventSchema,
]);

export type ApplicationLogEvent = z.infer<typeof ApplicationLogEventSchema>;
